[build-system]
requires = [
    "setuptools>=42",
    "setuptools_scm[toml]>=7.0.4",
    "wheel",
]

build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_scheme = "guess-next-dev"
local_scheme = "no-local-version"
write_to = "src/_version.py"